-- Real MCQ quiz: HR manages a bank of questions, employees take one
-- randomly-sampled 10-question attempt (one attempt each), and the result
-- feeds into the employee's overall_score (see syncEmployeeAggregates).
-- Same visibility pattern as elsewhere: private tables are self-or-HR
-- readable, plus a public ts_quiz_leaderboard projection kept in sync by
-- Server Actions using the service-role key. No insert/update/delete
-- policies — all writes happen server-side.

create table if not exists public.ts_quiz_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null unique,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('a', 'b', 'c', 'd')),
  is_active boolean not null default true,
  created_by uuid references public.ts_employees(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.ts_quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null unique references public.ts_employees(id) on delete cascade,
  score int not null check (score between 0 and 100),
  correct_count int not null,
  total_questions int not null,
  completed_at timestamptz not null default now()
);

-- Public projection, same reasoning as ts_leaderboard: lets everyone see
-- rankings without granting broad read access to raw attempt rows.
create table if not exists public.ts_quiz_leaderboard (
  employee_id uuid primary key references public.ts_employees(id) on delete cascade,
  full_name text not null,
  department text,
  score int not null default 0,
  correct_count int not null default 0,
  total_questions int not null default 0,
  completed_at timestamptz not null default now()
);

alter table public.ts_quiz_questions enable row level security;
alter table public.ts_quiz_attempts enable row level security;
alter table public.ts_quiz_leaderboard enable row level security;

create policy "Employees can view active quiz questions" on public.ts_quiz_questions
  for select to authenticated using (is_active = true);
create policy "HR can view all quiz questions" on public.ts_quiz_questions
  for select to authenticated using (public.ts_current_role() = 'hr');

create policy "Employees can view own quiz attempt" on public.ts_quiz_attempts
  for select to authenticated using (employee_id = auth.uid());
create policy "HR can view all quiz attempts" on public.ts_quiz_attempts
  for select to authenticated using (public.ts_current_role() = 'hr');

create policy "Anyone authenticated can view the quiz leaderboard" on public.ts_quiz_leaderboard
  for select to authenticated using (true);

insert into public.ts_quiz_questions (question, option_a, option_b, option_c, option_d, correct_option) values
  ('What is the primary function of a solar photovoltaic (PV) cell?', 'Store electricity', 'Convert sunlight directly into electricity', 'Convert wind into electricity', 'Heat water directly', 'b'),
  ('Which material is most commonly used to manufacture solar cells?', 'Copper', 'Silicon', 'Aluminum', 'Iron', 'b'),
  ('What does "kWp" stand for in solar panel specifications?', 'Kilowatt-peak', 'Kilowatt-per-hour', 'Kilo-watt-power', 'Kilowatt-panel', 'a'),
  ('What is the typical lifespan of a well-maintained solar panel?', '2-5 years', '10-12 years', '25-30 years', '50-60 years', 'c'),
  ('Which of these best describes "net metering"?', 'Measuring panel temperature', 'Crediting excess solar power sent back to the grid', 'Measuring panel weight', 'A type of inverter', 'b'),
  ('Which device converts the DC electricity generated by solar panels into usable AC electricity?', 'Transformer', 'Inverter', 'Battery', 'Charge controller', 'b'),
  ('Which factor most reduces a solar panel''s energy output?', 'Cool temperatures', 'Shading or dust on the panel surface', 'Clear blue skies', 'Panels facing south (in the northern hemisphere)', 'b'),
  ('What is the recommended general maintenance practice for solar panels?', 'Regular cleaning to remove dust and debris', 'Painting the panels annually', 'Covering panels at night', 'Watering the panels daily', 'a'),
  ('In a grid-tied solar system with no battery backup, what typically happens during a power outage?', 'The solar system continues supplying the home as normal', 'The system automatically shuts down for safety', 'The panels switch to wind mode', 'Panel output doubles', 'b'),
  ('Why does TerraRex Energy emphasize proper panel orientation and tilt angle during installation?', 'To maximize sunlight capture and energy yield', 'To make panels look uniform', 'To reduce installation cost only', 'It has no effect on output', 'a')
on conflict (question) do nothing;
